sonar.projectKey=farmdirect-secure-devsecops
sonar.projectName=FarmDirect Secure DevSecOps Platform
sonar.sourceEncoding=UTF-8

sonar.sources=app/backend,app/frontend/src
sonar.tests=app/backend/tests
sonar.test.inclusions=app/backend/tests/**/*.test.js

sonar.exclusions=**/node_modules/**,**/dist/**,**/coverage/**,**/*.png,**/*.jpg,**/*.jpeg,**/*.gif,**/*.webp,**/*.ico

sonar.javascript.lcov.reportPaths=app/backend/coverage/lcov.info