services:
  database:
    volumes:
      - ../app/database/seed.staging.sql:/docker-entrypoint-initdb.d/02-seed-staging.sql:ro

  backend:
    ports:
      - "5001:5000"

  frontend:
    ports:
      - "8082:8080"