apiVersion: v1
kind: ConfigMap
metadata:
  name: farmdirect-backend-config
  namespace: farmdirect
data:
  PORT: "5000"
  DB_HOST: "database"
  DB_PORT: "5432"
  CLIENT_ORIGIN: "http://localhost:8083"