apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - backend-configmap.yaml
  - database-service.yaml
  - database-statefulset.yaml
  - backend-service.yaml
  - backend-deployment.yaml
  - frontend-deployment.yaml
  - frontend-service.yaml
  - backend-hpa.yaml
  - backend-pdb.yaml
  - frontend-pdb.yaml
  - database-network-policy.yaml
  - resource-quota.yaml